import React from 'react'
import ReactDOM from 'react-dom/client'

import App from './App.tsx'

import './styles.css'

// biome-ignore lint/style/noNonNullAssertion: This was generated by Vite
ReactDOM.createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)
